### ISSUE TITLE
implement generate_biom_table

### ISSUE THREAD

**Issue by josenavas** [biocore/deblur#15]

**Comment by ekopylova** [comment]
@amnona have you started anything with this? If not, I'll write this function. Thanks!

**Comment by amnona** [comment]
I have a function that does it in my (ugly) improvised code.
It takes a directory of deblurred dereplicated fasta files and joins them
into one text biom table using a dictionary to count how many reads from
each sample file. The output is a text biom table and a fasta file (since
deblurring is like de-novo)
Attached.
Maybe better if you rewrite it?
Also, can we incorporate the sequences themselves into the biom table
instead of working with biom + fasta file? (in a metadata field per feature
in the biom table)?

On Mon, Jul 27, 2015 at 1:43 PM, Evguenia Kopylova <notifications@github.com

**Comment by wasade** [comment]
Is this a tab delimited (e.g., classic OTU table) or a BIOM-format v1.0
table?

For compatibility with QIIME, please ensure the data are either in
BIOM-format v1.0 or v2.1.

**Comment by wasade** [comment]
...that, and for file size as tab delim is a dense representation

**Comment by amnona** [comment]
It is tab delimited.
Is there a way to include the sequence of each OTU inside the biom table?
can it be in the OTUID or as a metadata?

**Comment by wasade** [comment]
That's not a BIOM table then

Yes, BIOM v1.0 and v2.x support arbitrary metadata for the samples and
observations. Details can be found here:

http://biom-format.org/

**Comment by ekopylova** [comment]
@amnona , is [this](https://github.com/amnona/deblurring/blob/master/CreateTable.py) the code you have?

**Comment by ekopylova** [comment]
what about the taxonomy, we decided that it will be determined separately? We would need an actual fasta file for 'OTU' representation in order to do that. If deblurring only outputs the biom table with the sequence as metadata, it won't be possible to run assign_taxonomy.py ..

**Comment by josenavas** [comment]
As I've proposed before, please be as consistent as other sequence clustering algorithms that are in QIIME. Generating as output an OTU map and a FASTA (rep set) file will make the integration of deblur in QIIME extremely easy, as there are already mechanisms in place to get the OTU table from such data.

E.g. the output of pick_otus.py in QIIME is an OTU map. From there we can run make_otu_table.py to generate the BIOM table. I highly recommend to use this path so we don't duplicate code inside the lab.

**Comment by josenavas** [comment]
Also, do not assume that the code is run in parallel. The code should expect to be run in serial, as a single input file. Don't try to implement "workflow" alike steps as this will complicate any further optimization down the process.

**Comment by amnona** [comment]
Regarding biom format, there is the classical dilemma of size+speed (biom)
vs. easy interpretation and use without dependencies (tab delimited text).
I understand the advantage of non text biom, but it complicates the ease of
use in other programs (for example, i use matlab and in it it's hard to
import biom but easy to use text delimited)...
From my experience, i have never encountered an experiment where the tab
delimited biom table size was a problem (and while experiments are getting
bigger, so are the compute resources).
Maybe best to have both (or three if you want text/json/hdf5) options as
output (so the user selects the preferred output format, and we can set the
default to hdf5 if we think this is the most common use case)?

What do you think?

**Comment by amnona** [comment]
I'm not sure the pick_otus.py output format is relevant for deblurring:
1. Some reads are thrown away, and their identity is arbitrary
2. The whole deblurring is performed on the dereplicated fasta (again, we
lose the identity of each read)
3. All reads belonging to an OTU are identical, so again no use in keeping
the specific identity of each read.
4. This intermediate will greatly inflate the sizes and maybe slow
performance.

Maybe better to get directly the biom table as output? and have an
additional fasta file if needed?
What do you think?

**Comment by amnona** [comment]
I Agree that maybe it's best to have also the fasta file so it'll be easy
to combine with qiime (i.e. assign_taxonomy.py).
Another thing: since we don't have OTUs but sequences, maybe it'll be good
to just use the actual sequence as the OTUID in the biom table? so instead
of having the sequence as a field associated with the feature, we can just
have it as the name? This way it will prevent the same sequence getting
different IDs in different experiments and thus enable direct comparison of
the biom tables without the need to write new code to look at the fasta or
biom metadata?
but maybe it can cause problems? can qiime/biom handle an OTUid of a few
hundred ACGT letters?
What do you think?


On Mon, Jul 27, 2015 at 4:19 PM, Evguenia Kopylova <notifications@github.com

**Comment by ekopylova** [comment]
re: output OTU map and FASTA (rep set)
I agree with this output, at least as the default output, as it will allow easy integration into QIIME (assign_taxonomy.py and make_otu_table.py can be directly run on this). 
Note: vsearch allows the output of a .uc file during dereplication which can be used to expand the final OTU map for including all sequence ids previously collapsed, which is great.
 
re: parallelism - 'The code should expect to be run in serial, as a single input file'
I believe that's what we have been doing ..

re: storing sequence as OTUID in Biom table
@wasade @ElDeveloper @josenavas, is this possible/efficient (handling OTUID of a few hundred nucleotides)?

Thanks everyone!

**Comment by wasade** [comment]
No issues using nucleotide sequences as observation IDs. That is an awesome idea though as it would allow for merging tables natively.

**Comment by ElDeveloper** [comment]
MATLAB does have an HDF5 API ... just sayin' http://www.mathworks.com/help/matlab/hdf5-files.html

**Comment by ekopylova** [comment]
closed with PR #22
