### ISSUE TITLE
Deblur workflow output 

### ISSUE THREAD

**Issue by bishnuadhikari** [biocore/deblur#176]
I was running deblur workflow using seqs.fna, output from split_libraries_fastq.py as demonstrated in the example, however, I was getting different outputs than those mentioned in the example. I am getting deblur_working_dir, deblur.log and split as outputs instead of getting reference-hit.seqs.fa, reference-non-hit.biom, reference-non-hit.biom, reference-non-hit.seqs.fa, all.biom, and all.seqs.fa as mentioned in the example. I used the deblur workflow previously once but was getting the exact outputs. I am wondering whether, the workflow has changed or something wrong, and I didn't see any changes in the github example usage. I didn't have any ideas how to use the information in current directories for futher downstream analysis if the output is correct. I would really appreciate your suggestions and feebacks on this issue. 

Thank you 

Best Regards
Bishnu Adhikari

**Comment by amnona** [comment]
Hi Bishnu,
deblur_working_dir is a temporary directory produced by deblur during the
processing.
If you see this directory but not the reference-hit.biom etc. it means one
of the two:
1. deblur is still running
2. deblur failed during the processing.
Did deblur output some error message?
Also, you can look at the deblur.log file to see exactly where the problem
occurs.
I would recommend deleting deblur.log (since new output is appended to the
log file rather than rewriting it) and then rerunning deblur with more
verbose log reporting. i.e.
deblur (ALL YOUR PARAMETERS) --log-level 1
Can you copy the exact command you used for running deblur, and attach the
deblur.log file after rerunning?

Cheers
Amnon

**Comment by bishnuadhikari** [comment]
Dear Amnon,

Thank you very much for the quick reply. I have re-ran as you suggested and
got the following error message. The exact code I have entered is also
shown below.

(deblurenv) bxa015@js-16-234:~/Kemin-BA/joined_pairend/processed_seqs/split_kemin$
deblur workflow --seqs-fp seqs.fna --output-dir output -t 400
Traceback (most recent call last):
  File "/home/bxa015/miniconda3/envs/deblurenv/bin/deblur", line 684, in
<module>
    deblur_cmds()
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/click/core.py",
line 722, in __call__
    return self.main(*args, **kwargs)
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/click/core.py",
line 697, in main
    rv = self.invoke(ctx)
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/click/core.py",
line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/click/core.py",
line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/click/core.py",
line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bxa015/miniconda3/envs/deblurenv/bin/deblur", line 655, in
workflow
    outputfasta_fp=outputfasta_fp, minreads=min_reads)
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/deblur/workflow.py",
line 705, in create_otu_table
    obs = scipy.sparse.dok_matrix((1E9, len(deblurred_list)),
dtype=np.double)
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/scipy/sparse/dok.py",
line 88, in __init__
    self._shape = check_shape((M, N))
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/scipy/sparse/sputils.py",
line 281, in check_shape
    new_shape = tuple(operator.index(arg) for arg in args)
  File
"/home/bxa015/miniconda3/envs/deblurenv/lib/python3.5/site-packages/scipy/sparse/sputils.py",
line 281, in <genexpr>
    new_shape = tuple(operator.index(arg) for arg in args)
TypeError: 'float' object cannot be interpreted as an integer
(deblurenv) bxa015@js-16-234
:~/Kemin-BA/joined_pairend/processed_seqs/split_kemin$


Best Regards
Bishnu Adhikari
PhD Candidate
University of Arkansas
Poultry Science POSC O-220
1260 W. Maple
Fayetteville, AR 72701
4798562305

**Comment by bishnuadhikari** [comment]
Dear Amnon, 

Please find the deblur log ran a/c to your suggestions which also got the same error message as above when I gave following command. 
(deblurenv) bxa015@js-16-234:~$ deblur workflow --seqs-fp seqs.fna --output-dir output -t 400 --log-level 1

[deblur.log](https://github.com/biocore/deblur/files/2186150/deblur.log)
Thank you 
Regards
Bishnu Adhikari

**Comment by amnona** [comment]
Hi Bishnu,
This seems to be a bug in the deblur code due to a change in how python
treats 1E9 (float rather than int) in new python versions.
We're working on a fix. Will update once it is ready.

Thanks for the report
Amnon

**Comment by bishnuadhikari** [comment]
Dear Amnona,

Thank you very much for the information. Please let me know once it is
fixed. I hope it will be fixed soon.

Best Regards
Bishnu Adhikari
PhD Candidate
University of Arkansas
Poultry Science POSC O-220
1260 W. Maple
Fayetteville, AR 72701
4798562305

**Comment by bishnuadhikari** [comment]
Dear Amnon,

Good afternoon,

I am just checking whether bug in the deblur workflow is fixed or not. I
really appreciate you kind support and help.

Thank you

Best Regards
Bishnu Adhikari
PhD Candidate
University of Arkansas
Poultry Science POSC O-220
1260 W. Maple
Fayetteville, AR 72701
4798562305

**Comment by amnona** [comment]
Hi,
Should be ready in 24hrs. Will mail when merged and ready for install.

Thanks
Amnon

**Comment by bishnuadhikari** [comment]
Dear Amnon,


Thank you very much for the information. I am eagerly waiting to run it
again.

Appreciated.

Best Regards
Bishnu Adhikari
PhD Candidate
University of Arkansas
Poultry Science POSC O-220
1260 W. Maple
Fayetteville, AR 72701
4798562305

**Comment by amnona** [comment]
Hi Bishnu,
we have a new dev. version on github that should take care of this bug.

Can you try to install the github version as follows:
source activate deblurenv
conda uninstall deblur
pip install git+git://github.com/biocore/deblur

and then try to run deblur on your data?
Please let me know if it works now or if the bug is still occurring.

Thanks,
Amnon

**Comment by bishnuadhikari** [comment]
Dear Amnon,

Thank you very much for the information and support. Now, I got the results
and worked perfectly. I want to know your suggeston regarding trim length;
the median sequence length of the reads is 548 since each forward and
reverse reads were 300 bp and joined together. At this condition, what trim
length will be optimum based on your experience?

Thank you

Best Regards
Bishnu Adhikari
PhD Candidate
University of Arkansas
Poultry Science POSC O-220
1260 W. Maple
Fayetteville, AR 72701
4798562305

**Comment by amnona** [comment]
Hi Bishnu,
happy to hear the fix worked :)

Regarding the trim lengths,
based on my experience, the reverse reads tend to have a very high error
rate. Since in the current deblur implementation, a constant error rate is
assumed for all positions, using the reverse reads will force using a high
error correction rate, which will reduce the sensitivity.
Therefore, the default deblur error profile is for the forward reads only.
What I usually do is work only with the forward reads (without merging the
reverse reads). Personally, i also like to work with even shorted reads
(i.e. trim length=200 or 250) again due to the higher error rate at the
ends of long reads. So if you choose this option, just take the forward
reads and use trim length=200 / 250
If you want to keep the merged reverse reads, i would recommend just
concatenating the forward and reverse reads (i.e. if you have 1000 reads,
join the forward and reverse for each of the 1000 reads without merging -
so getting 1000 reads of length 300bp+300bp=600bp). Then running deblur
with trim length 600 and then un-concatenating to 2*300bp reads and then
merging if you want.
If you choose to run deblur on the merged reads instead, remember that all
reads shorter than the trim length will be discarded.

In general, there is a balance between read length (which affects the
phylogenetic resolution) and noise (which affects the ability to tell apart
very close sequences in your sample). Personally i think 250bp is enough
phylogenetic resolution for most scenarios compared to the price you pay
for increased noise. But this is a matter of taste and the specific use
case.

BTW: what sequencing primers did you use (i.e. 515F, 806R etc.)

Let me know how it goes,
Amnon

**Comment by bishnuadhikari** [comment]
Dear Amnon,

Good morning!

Thank you very much for your suggestions. I have used different primer sets
(27F and 533R) and have barcodes (4nt) on both forward and reverse reads as
shown in the attached image. I have to join them and extract barcodes in
order to demultiplex them. I sought whether QIIME2 has developed piplelines
for such type of library, but didn't succeed. So, I found using deblur
workflow outside QIIME2 from the sequences that I got from
split_libraries_fastq.py option of QIIME1 and importing the output of
deblur later will be the best choice so far?, based on my research. I did
quality filtering using trimmomatic and the reads also passed quality score
20 during demultiplexing step. Do you have any suggestions for this type of
sequence that are already joined and demultiplexed? I appreciate your
suggestions and willingness to help.

Thank you

Best Regards
Bishnu Adhikari
PhD Candidate
University of Arkansas
Poultry Science POSC O-220
1260 W. Maple
Fayetteville, AR 72701
4798562305

**Comment by amnona** [comment]
Hi Bishnu,
I don't know a lot about qiime2 - maybe best to ask in the qiime2 forum
about the sort of data you start with (probably the qiime2 developers will
be happy to hear about new inputs and how to incorporate into qiime2
pipelin2).
currently, the steps you mentioned (preprocessing in qiime1 and then
running deblur standalone and then importing to qiime2) make sense (i
sometimes use a similar general approach). Quality filtering to 20 is good.
In general, if you process after the pair-merging, you risk ignoring
bacteria where the amplified region size is bigger than (600 - overlap
requirement). I don't know if this is a concern for the region you are
sequencing and in any case, amplicon sequencing does not capture all
bacteria, so this is not a show stopper.
I would recommend deblurring to length 200 or 250, but maybe best option is
to try different trim lengths (i.e. 200,250 and 500) and compare the
results so see what payoff you have between read length and error rate.

**Comment by wasade** [comment]
Closing as the seed issue of casting 1E9 has been addressed.
