### ISSUE TITLE
problem if after trimming+dereplication we have 1 sequence left

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#66]
mafft failes (only 1 sequence to align)
so a samples containing only 1000 identical reads will fail in the mafft stage

**Comment by wasade** [comment]
This is a valid issue especially in low diverse samples where some may end up with low coverage by chance. Since the low coverage samples are not removed prior to execution of deblur, this is a important bug that needs to be resolved if it has not been done so already. 

@amnona do you know the status of this?

**Comment by amnona** [comment]
since this is before deblurring, it will only be a problem if all the reads don't have read errors, which is very not probable...
anyway, added a check in the workflow and skip msa if single sequence.
