### ISSUE TITLE
add taxonomy script/embed in pipeline

### ISSUE THREAD

**Issue by amnona** [biocore/deblur#79]
the people want taxonomy in their biom table
we can:
1. supply an additional script (using qiime rdp/other option?) to add taxonomy
2. add this script as an optional step in the pipeline (and have it as optional package dependency)

**Comment by josenavas** [comment]
Suggest redirecting to Qiime - we will not be able to call QIIME internally due to dependency conflicts and I don't think it is useful to re-invent the wheel if there is already a script in Qiime that does that. Once that script is available in QIIME2 and deblur is also there it should be simpler to explain the pipeline (note that this is similar as split libraries, so it is just another step that we can link at the end)

**Comment by wasade** [comment]
Agree with @josenavas, taxonomy assignment is a logically distinct issue resolved in other packages
